// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phharrdxkcbuxrzaafmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoaGFycmR4a2NidXhyemFhZm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjM3MzAsImV4cCI6MjA3MjgzOTczMH0.iQUjlynrUt6Qby_HLhZuFOYM9G_g8BAJ91TPONeDuHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});